import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
padding.x = 5
padding.y = 5

decorations = "Buttonless"

opacity = 0.8
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14

[env]
TERM = "xterm-256color"

